# Generated by Django 5.2.2 on 2025-11-18 16:05

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('None', 'None'), ('Transfer', 'Transfer'), ('Credit Alert', 'Credit Alert'), ('Debit Alert', 'Debit Alert'), ('Sent Payment Request', 'Sent Payment Request'), ('Recieved Payment Request', 'Recieved Payment Request'), ('Funded Credit Card', 'Funded Credit Card'), ('Withdrew Credit Card Funds', 'Withdrew Credit Card Funds'), ('Deleted Credit Card', 'Deleted Credit Card'), ('Added Credit Card', 'Added Credit Card'), ('Transfer Cancelled', 'Transfer Cancelled'), ('Goal Created', 'Goal Created'), ('Goal Updated', 'Goal Updated'), ('Goal Completed', 'Goal Completed'), ('Goal Deleted', 'Goal Deleted'), ('Goal Amount Added', 'Goal Amount Added'), ('Loan Request Accepted', 'Loan Request Accepted'), ('Loan Request Disbursed', 'Loan Request Disbursed'), ('Loan Request Under Review', 'Loan Request Under Review'), ('Loan Request Rejected', 'Loan Request Rejected')], default='none', max_length=100),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=12, max_length=20, prefix='LOAN', unique=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('duration_months', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('completed', 'Completed')], default='under_review', max_length=50)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_disbursed', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_requested'],
            },
        ),
    ]
