from django.db import models
from userauths.models import User 
from accounts.models import Account
from shortuuid.django_fields import ShortUUIDField

from decimal import Decimal
import uuid
import datetime


TRANSACTION_TYPE = (
    ("transfer", "Transfer"),
    ("recieved", "Recieved"),
    ("withdraw", "withdraw"),
    ("refund", "Refund"),
    ("request", "Payment Request"),
    ("none", "None")
)

TRANSACTION_STATUS = (
    ("failed", "failed"),
    ("completed", "completed"),
    ("pending", "pending"),
    ("processing", "processing"),
    ("request_sent", "request_sent"),
    ("request_settled", "request settled"),
    ("request_processing", "request processing"),

)


CARD_TYPE = (
    ("select_card", "select card"),
    ("verve", "verve"),
    ("master", "master"),
    ("visa", "visa"),

)

GOAL_TYPE = (
    ("Select_Goal", "Select Goal"),
    ("Savings", "Savings"),
    ("Investment", "Investment"),
    ("Emergency", "Emergency"),
    ("Travel", "Travel"),
    ("Education", "Education"),
    ("Business", "Business"),
)

LOAN_STATUS = (
    ("under_review", "Under Review"),
    ("approved", "Approved"),
    ("rejected", "Rejected"),
    ("disbursed", "Disbursed"),
    ("completed", "Completed"),
)


NOTIFICATION_TYPE = (
    ("None", "None"),
    ("Transfer", "Transfer"),
    ("Credit Alert", "Credit Alert"),
    ("Debit Alert", "Debit Alert"),
    ("Sent Payment Request", "Sent Payment Request"),
    ("Recieved Payment Request", "Recieved Payment Request"),
    ("Funded Credit Card", "Funded Credit Card"),
    ("Withdrew Credit Card Funds", "Withdrew Credit Card Funds"),
    ("Deleted Credit Card", "Deleted Credit Card"),
    ("Added Credit Card", "Added Credit Card"),
    ("Transfer Cancelled", "Transfer Cancelled"),

    # -------------------------
    # GOAL NOTIFICATIONS - Recipient automatically added to your list
    # -------------------------
    ("Goal Created", "Goal Created"),
    ("Goal Updated", "Goal Updated"),
    ("Goal Completed", "Goal Completed"),
    ("Goal Deleted", "Goal Deleted"),
    ("Goal Amount Added", "Goal Amount Added"),
    
    # Loan 
    ("Loan Request Accepted", "Loan Request Accepted"),
    ("Loan Request Disbursed", "Loan Request Disbursed"),
    ("Loan Request Under Review", "Loan Request Under Review"),
    ("Loan Request Rejected", "Loan Request Rejected"),
    
)


class Transaction(models.Model):
    transaction_id = ShortUUIDField(unique=True, length=15, max_length=20, prefix="TRN")
   
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="user")
    amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    description = models.CharField(max_length=1000, null=True, blank=True)
   
    reciever = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="reciever")
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="sender")
   
    reciever_account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, related_name="reciever_account")
    sender_account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, related_name="sender_account")

    status = models.CharField(choices=TRANSACTION_STATUS, max_length=100, default="pending")
    transaction_type = models.CharField(choices=TRANSACTION_TYPE, max_length=100, default="none")

    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=False, null=True, blank=True)

    def __str__(self):
        try:
            return f"{self.user}"
        except:
            return f"Transaction"

# Card
class CreditCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card_id = ShortUUIDField(unique=True, length=5, max_length=20, prefix="TINCARD", alphabet="1234567890")

    cvv = ShortUUIDField(unique=True, length=3, max_length=20, alphabet="1234567890")
    number = ShortUUIDField(unique=True, length=16, max_length=20, alphabet="1234567890")

    # name = models.CharField(max_length=100) # the name should come from the KYC
    # month = models.IntegerField(editable=False) # this is autogenerated
    # year = models.IntegerField(editable=False) # this is autogenerated

    month = models.IntegerField(blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)

    amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    card_type = models.CharField(choices=CARD_TYPE, max_length=20, default="select_card")
    card_status = models.BooleanField(default=True)

    date = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # Auto-generate month + year only if empty
        if not self.month or not self.year:
            now = datetime.datetime.now()
            self.month = now.month
            self.year = (now.year + 4) % 100  # store only last two digits (e.g., 2029 → 29)

        super().save(*args, **kwargs)

    @property
    def expiry_mm_yy(self):
        return f"{self.month:02d}/{self.year:02d}"

    def __str__(self):
        return f"{self.user}"


# Goal
class Goal(models.Model):
    gid = ShortUUIDField(unique=True, length=5, prefix="TINGOAL", alphabet="1234567890")

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    goal_type = models.CharField(max_length=50, choices=GOAL_TYPE, default="none")

    target_amount = models.DecimalField(max_digits=12, decimal_places=2)
    current_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    image = models.ImageField(upload_to="goals/", null=True, blank=True, default="goal.png")

    deadline = models.DateField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} - {self.user.username}"

    @property
    def progress_percentage(self):
        if self.target_amount == 0:
            return 0
        return (self.current_amount / self.target_amount) * 100

    @property
    def is_completed(self):
        return self.current_amount >= self.target_amount
    

# Recipient
class Recipient(models.Model):
    rid = ShortUUIDField(length=6, max_length=20, prefix="TINREC", alphabet="1234567890")

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_recipients")
    recipient_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="saved_by")

    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=50, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "recipient_user")  # prevents duplicates
        ordering = ['-date_added']

    def __str__(self):
        return f"{self.user} → {self.recipient_user}"
    

# Loan Request
class Loan(models.Model):
    loan_id = ShortUUIDField(unique=True, length=12, max_length=20, prefix="LOAN", alphabet="1234567890")

    # User applying
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Loan request info
    amount_requested = models.DecimalField(max_digits=12, decimal_places=2)
    amount_disbursed = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)

    purpose = models.CharField(max_length=200, null=True, blank=True)

    interest_rate = models.DecimalField(max_digits=5, decimal_places=2, default=10.00)  # 10%
    duration_months = models.IntegerField(default=1)

    # Status tracking
    status = models.CharField(max_length=50, choices=LOAN_STATUS, default="under_review")

    # Timestamps
    date_requested = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    date_disbursed = models.DateTimeField(null=True, blank=True)

    # Bank Account for disbursement
    account = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['-date_requested']

    def __str__(self):
        return f"Loan {self.loan_id} - {self.user.username}"

    @property
    def total_payable(self):
        """Interest included"""
        interest_amount = (self.interest_rate / Decimal(100)) * self.amount_requested
        return self.amount_requested + interest_amount

       
# Notification
class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    notification_type = models.CharField(max_length=100, choices=NOTIFICATION_TYPE, default="none")
    sender = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="notification_sender")
    reciever = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="notification_reciever")
    amount = models.IntegerField(default=0)
    is_read = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    nid = ShortUUIDField(length=10, max_length=25, alphabet="abcdefghijklmnopqrstuvxyz")
    
    class Meta:
        ordering = ["-date"]
        verbose_name_plural = "Notification"

    def __str__(self):
        return f"{self.user} - {self.notification_type}"


